### ISSUE TITLE
How to actually use the private key to recover

### ISSUE THREAD

**Issue by christianlundkvist** [Ambisafe/private_key_recovery_service#3]
I've been looking at this recovery tool and I've managed to get the private key out of an encrypted container using the tool.

It then says I can use this private key through MEW/MyCrypto to access the funds (which are in a separate smart contract). However it doesn't say *how* to do this. How do I actually interact with the smart contract, is there Solidity code or ABI anywhere?

**Comment by lastperson** [comment]
Right, so there is a function `forward(address _destination, uint _weiValue, bytes _data)` in your user contract. You can use it to make external calls from your storage contract. You can build the ABI in remix, or I will post it here in a couple of hours.

**Comment by christianlundkvist** [comment]
@lastperson Hey thanks! Sounds like it's a proxy contract basically? So I call that function from the Ethereum account that was stored in the encrypted container?

I suspect this would be a bit fiddly when doing token transfers right? I.e. the `destination` is the token address, and the `data` encodes the actual token transfer?

**Comment by lastperson** [comment]
that is exactly correct, though there is 2 contracts, one controls the access and the second one stores value and makes external orders.

**Comment by christianlundkvist** [comment]
@lastperson Ok so the tokens are stored in the Proxy contract, and so I need to figure out what the controller contract is that I actually need to call using the `forward` function? (I have the address of the proxy contract holding value). When I look at the proxy contract opcodes view I see at the very bottom this:

```
JUMPDEST
STOP
JUMPDEST
PUSH20 0xsomeEthereumAddressHere
JUMPDEST
SWAP1
JUMP
STOP
```

would that be the address of the controller contract?

**Comment by lastperson** [comment]
Call this on proxy to get the owner `contractOwner() returns(address)`

**Comment by christianlundkvist** [comment]
@lastperson Ok I got the owner address through the `contractOwner()` function. I'm noticing that my address that I control through the private key was not involved in any transaction to this particular contract. Is that private key just signing data that is then verified using `ecrecover`? And the `forward()` function is an alternate means of triggering the forwarding?

**Comment by lastperson** [comment]
Correct.

**Comment by christianlundkvist** [comment]
@lastperson Ok I was able to move the tokens out of the wallet using the `forward()` function, thanks for the help! May I suggest you build in a little helper function in the recovery package to help users with this? This was quite cumbersome. :)

**Comment by lastperson** [comment]
@christianlundkvist we have it on our TODO list. Are you interested in a solidity engineer position by any chance? If so, can you contact me at oleksii+careers🐌ambisafe.com ?

**Comment by christianlundkvist** [comment]
@lastperson 

> we have it on our TODO list.

Ok sounds good!

> Are you interested in a solidity engineer position

Thanks for the offer, but I'm keeping busy at ConsenSys & uPort! 😃
